eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
  settings:
    username: ${EUREKA_SETTINGS_USERNAME:eureka}
    password: ${EUREKA_SETTINGS_PASSWORD:password}
    roles: ${EUREKA_SETTINGS_ROLES:USER,EUREKA}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/auth/realms/oauth-demo

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
