eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/auth/realms/oauth-demo
    user:
      name: eureka
      password: password
      roles: USER,EUREKA
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0